---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - lct.kube.inspect
  resources:
  - taskdefines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lct.kube.inspect
  resources:
  - taskdefines/finalizers
  verbs:
  - update
- apiGroups:
  - lct.kube.inspect
  resources:
  - taskdefines/status
  verbs:
  - get
  - patch
  - update
