# permissions for end users to edit rpcruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lctcluster
    app.kubernetes.io/managed-by: kustomize
  name: rpcruntime-editor-role
rules:
- apiGroups:
  - lct.test.lct
  resources:
  - rpcruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lct.test.lct
  resources:
  - rpcruntimes/status
  verbs:
  - get
