# permissions for end users to edit taskdefines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/managed-by: kustomize
  name: taskdefine-editor-role
rules:
- apiGroups:
  - lct.kube.inspect
  resources:
  - taskdefines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lct.kube.inspect
  resources:
  - taskdefines/status
  verbs:
  - get
