apiVersion: lct.test.lct/v1
kind: ApiRuntime
metadata:
  labels:
    app.kubernetes.io/name: lctcluster
    app.kubernetes.io/managed-by: kustomize
  name: apiruntime-sample
spec:
  # TODO(user): Add fields here
